services:
  - type: web
    name: ggdove-cms-auth
    runtime: node
    buildCommand: ""
    startCommand: node index.js
    envVars:
      - key: OAUTH_CLIENT_ID
        sync: false
      - key: OAUTH_CLIENT_SECRET
        sync: false
